//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_ICON_WOLSCA_INBOXMANAGER    103
#define IDI_ICON_WOLSCA_INBOXMANAGER_A1 104
#define IDI_ICON_WOLSCA_INBOXMANAGER_A2 105
#define IDI_ICON_WOLSCA_INBOXMANAGER_A3 106
#define IDI_ICON_WOLSCA_INBOXMANAGER_A4 107
#define IDI_ICON_WOLSCA_INBOXMANAGER_A5 108
#define IDI_ICON_WOLSCA_INBOXMANAGER_A6 109
#define IDI_ICON_WOLSCA_INBOXMANAGER_A7 110
#define IDR_GIF_BUSY                    111
#define IDR_BMP_LOGO                    112

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 102
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
